export const CHANGE_STATE_TO_TRUE = 'CHANGE_STATE_TO_TRUE';
export const CHANGE_STATE_TO_FALSE = 'CHANGE_STATE_TO_FALSE';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const CHANGE_STATE_MAIN = 'CHANGE_STATE_MAIN';